version: '3'
services:
  frontend:
    build:
      context: .
      args:
        label: frontend
        upstream: http://middle:3000/api
    external_links:
    - middle:middle
    ports:
    - "3000:3000"
  middle:
    build:
      context: .
      args:
        label: middle
        upstream: http://backend:3000/api
    external_links:
    - backend:backend
    expose:
    - "3000"
  backend:
    build:
      context: .
      args:
        label: backend
    expose:
    - "3000"
